# http://en.wikipedia.org/wiki/Chart_of_accounts#Balance_Sheet_Accounts

ledger = [
    {
        id: 1
        amount: 10      # the cost of the item etc.
        currency: 'GBP' # the currency of the item needs to match that of the benefactor's account
        time: '2013-01-23T11:09:52.463Z'
        transactions:
            # The key is the id of the user.
            'user:radek': [
                {
                    amount: -10.00     # total cost of the item paid from this account
                    account_id: 'hsbc' # id of the account for this user
                    description: 'An apple I paid for' # description I chose
                    category: 'My one'                 # my personal category
                } , {
                    amount: 4.00   # but we have borrowed credit to someone else
                    account_id: 'user:baruska'
                    description: '%description% shared with %user%' # autogenerated, updated based on the above text
                }
            ]
            'user:baruska': [
                {
                    amount: -4.00 # a credit received from us
                    account_id: 'user:radek'
                    description: 'An apple %user% paid for' # autogenerated, could be changed
                    category: 'Their one'                   # their personal category
                }
            ]
        ]
    }
]

users = [
    {
        id: 'user:radek':
        name: 'Radek'
        password: '&#!'
        linked: [ 'user:baruska' ] # users we are linked to, can share expenses with...
        accounts:
            'hsbc':
                type: 102          # US GAAP 102 Bank Accounts
                currency: 'GBP'
            'user:baruska':
                type: 103          # US GAAP 103 Accounts Receivable (Debtors)
                currency: 'GBP'
    } , {
        id: 'user:baruska'
        name: 'Baruška'
        password: '&#!'
        linked: [ 'user:radek' ]    # users we are linked to, can share expenses with...
        accounts:
            'user:radek':
                type: 201           # US GAAP 201 Accounts Payable (Creditors)
    }
]

# (a) List all expenses in the last month:
###
    1. Go through the `ledger` looking into `transactions` checking if we see our key.
    2. Show for each transaction (on a separate line?) the credit and debit achieving the total of how much we spent.
###

# (b) List all loans we have with a user:
###
    1. Go through the `ledger` looking into `transactions` checking if we see our key.
    2. For each transaction if we see an `account_id` that corresponds with 103 or 201, add it to the listing.
###

# (c) Get current balance on an account:
###
    1. Go through the `ledger` looking into `transactions` checking if we see our key.
    2. For each transaction if see an `account_id` that corresponds to a specific one we are looking for, increase count.
###

# (d) Update a previous transaction:
###
    1. Filter the `ledger` based on a specific key.
    2. Merge this info with out accounts info to get the picture of the transaction that took place.
    3. Simply replace this entry with a new one preserving the descriptions and categories in other users if we have not changed the description.
###