# http://en.wikipedia.org/wiki/Chart_of_accounts#Balance_Sheet_Accounts

transactions = [
    {
        id: 1
        type: 'debit'   # we pay someone outside of 'us'
        amount: 10      # the cost of the item etc.
        currency: 'GBP' # the currency of the item needs to match that of the benefactor's account
        time: '2013-01-23T11:09:52.463Z'
        users: [ 1, 2 ] # which users were involved (for quick access)
    }
]

users =
    # Me.
    1:
        name: 'Radek'
        password: '&#!'
        accounts:
            1:
                type: 102      # US GAAP 102 Bank Accounts
                balance: -10.00
                currency: 'GBP'
            2:
                type: 103      # US GAAP 103 Accounts Receivable (Debtors)
                user: 2        # this is the user that got our credit (our debtor)
                balance: 4.00
                currency: 'GBP'
        
        transactions:
            1:
                description: 'An apple I paid for' # description I chose
                category: 15                       # my personal category
                # Show me the money!
                trail: [
                    {
                        'amount': -10.00 # total cost of the item paid from this account
                        'account_id': 1
                    } , {
                        'amount': 4.00   # but we have borrowed credit to someone else
                        'account_id': 2
                    }
                ]
        
        linked: [ 2 ] # users we are linked to, can share expenses with...
    
    # Them.
    2:
        name: 'Baruška'
        password: '&#!'
        accounts:
            1:
                type: 201      # US GAAP 201 Accounts Payable (Creditors)
                user: 1        # this is the user that gave us credit (a creditor)
                balance: -4.00
        
        transactions:
            1:
                description: 'An apple he paid for' # description can be changed
                category: 9                         # their personal category or null
                trail: [
                    {
                        'amount': -4.00 # a credit
                        'account_id': 1
                    }
                ]

        linked: [ 1 ] # users we are linked to, can share expenses with...
    }
]

# Rules:
    1. The system works out client-side what the actual amount should be applied from % or number amount.
    2. When editing an entry, the % split is worked out from the actual amounts back.
    3. One cannot update entries applied to accounts payable accounts as the other party has control over that.
    4. Descriptions generated for the other party will say something like "%my_description% paid by %user%" but can be changed.
    5. Categories for transactions can be unset in which case they may be flagged up in the UI.
    6. Accounts for debtors and creditors are autogenerated in the backend once we link accounts together.

# To get my (share of) expenses:
    1. For our user collection traverse all transactions of type 'debit'.
    2. For each transaction get the time and description.
    3. For each transaction, then, show the debit and credit applied to show the total cost.
    4. The actual +/- amount will be reflected by totalling all the amounts in the transaction list of our user.
    5. To show which account the amount was applied, fetch the account by its link from the transaction.

# To update our expense amount.
    1. Update or not the init date of the transaction.
    1. If the description did not change, traverse all users involved and save their categories and descriptions for the transaction.
    2. Save the transaction anew potentially with original descriptions and categories for other users.
    3. Remove the original transaction from the list and remove all references in transactions of users dict.