# http://en.wikipedia.org/wiki/Chart_of_accounts#Balance_Sheet_Accounts

ledger = [
    {
        amount: 10      # the cost of the item etc.
        currency: 'GBP' # the currency of the item needs to match that of the benefactor's account
        time: '2013-01-23T11:09:52.463Z'
        transactions:
            # The key is the id of the user.
            'user:radek': [
                {
                    amount: -10.00     # total cost of the item paid from this account
                    account_id: 'hsbc' # id of the account for this user
                    description: 'An apple I paid for' # description I chose
                    category: 'My one'                 # my personal category
                } , {
                    amount: 4.00   # but we have borrowed credit to someone else
                    account_id: 'user:baruska'
                    description: 'An apple I paid for shared with %user%' # autogenerated, could be changed
                }
            ]
            'user:baruska': [
                {
                    amount: -4.00 # a credit received from us
                    account_id: 'user:radek'
                    description: 'An apple %user% paid for' # autogenerated, could be changed
                    category: 'Their one'                   # their personal category
                }
            ]
        ]
    }
]

users = [
    {
        id: 'user:radek':
        name: 'Radek'
        password: '&#!'
        linked: [ 'user:baruska' ] # users we are linked to, can share expenses with...
        accounts:
            'hsbc':
                type: 102          # US GAAP 102 Bank Accounts
                currency: 'GBP'
            'user:baruska':
                type: 103          # US GAAP 103 Accounts Receivable (Debtors)
                currency: 'GBP'
    } , {
        id: 'user:baruska'
        name: 'Baruška'
        password: '&#!'
        linked: [ 'user:radek' ]    # users we are linked to, can share expenses with...
        accounts:
            'user:radek':
                type: 201           # US GAAP 201 Accounts Payable (Creditors)
    }
]